module.exports.config = {
    name: "say",
    version: "1.0.2",
    hasPermssion: 0,
    credits: "Shaan",
    description: "check the amount of yourself or the person tagged",
    commandCategory: "without prefix",
    usages: "[tag]",
    cooldowns: 5
};

module.exports.run = async function ({ api, event, args }) {
    try {
        const { createReadStream, unlinkSync } = global.nodemodule["fs-extra"];
        const { resolve } = global.nodemodule["path"];
        
        // Get the content of the message (reply or typed)
        var content = (event.type == "message_reply") ? event.messageReply.body : args.join(" ");
        
        // Set language to Urdu ('ur' language code)
        var languageToSay = 'ur'; // Hardcode to 'ur' for Urdu
        
        var msg = content; // No need to slice here, just take the full message as is
        
        // Define the file path to save the audio
        const path = resolve(__dirname, 'cache', `${event.threadID}_${event.senderID}.mp3`);
        
        // Download the audio file generated by Google Translate TTS for Urdu
        await global.utils.downloadFile(`https://translate.google.com/translate_tts?ie=UTF-8&q=${encodeURIComponent(msg)}&tl=ur&client=tw-ob`, path);
        
        // Send the audio message as an attachment to the thread
        return api.sendMessage({ attachment: createReadStream(path) }, event.threadID, () => unlinkSync(path));
    } catch (e) {
        return console.log(e);
    }
};